### ISSUE TITLE
貌似有intel网卡的驱动了 dalao有试试么

### ISSUE THREAD

**Issue by aouone** [mytianer/gs65-9sd-hackintosh#1]
maos

**Comment by mytianer** [comment]
看了一下，没怎么看明白，C++我也不会，太复杂了，感觉实用性不高，你现在黑苹果完美程度怎么样了

**Comment by aouone** [comment]
基本还好吧 但是就是用了真三码之后 锁屏界面会卡顿几秒 用了NoTouchID也还是会卡

**Comment by Guochengjie** [comment]
大佬好，现在intel无线能驱动了～
https://github.com/OpenIntelWireless/itlwm
另外问问10.15.7能跑嘛

**Comment by mytianer** [comment]
10.15.7已经升了，完全没问题的，注意clover好像要5120以下，不要用新的，新的好像换opencore了

**Comment by mytianer** [comment]
已驱动
