### ISSUE TITLE
蓝牙，触控板些许问题

### ISSUE THREAD

**Issue by Orz-Orz-L** [mytianer/gs65-9sd-hackintosh#4]
你好，我碰到了一些问题请教一下：
1、蓝牙不可用，然后尝试了重新定制usb，问题依旧
2、触控板可以单指多指控制移动、但是点击无效
3、睡眠唤醒后键盘无法使用，只能强制关机
以下是一些截图，还请帮忙分析一下是什么原因？
![image](https://user-images.githubusercontent.com/117557199/200452296-4453dae7-6a1d-4ffa-aff3-358ba5374a0b.png)
![image](https://user-images.githubusercontent.com/117557199/200452376-53b5f999-8926-4842-8583-f0a66697c76a.png)
![image](https://user-images.githubusercontent.com/117557199/200452414-94678f5d-51ef-4105-933f-9241f8afb1e6.png)
![image](https://user-images.githubusercontent.com/117557199/200450440-9bdefe02-49fb-4ef2-8cfa-9d97876f0b25.png)
![image](https://user-images.githubusercontent.com/117557199/200451935-09cd048d-60ed-4230-86da-a26d339a2afa.png)
[跑码.txt](https://github.com/mytianer/gs65-9sd-hackintosh/files/9956853/default.txt)

**Comment by mytianer** [comment]
我的配置里蓝牙驱动没有打开，其它问题解决了吗。我升了vetura之后感觉问题挺多的，你的怎么样？

**Comment by mytianer** [comment]
> 你好，我碰到了一些问题请教一下： 1、蓝牙不可用，然后尝试了重新定制usb，问题依旧 2、触控板可以单指多指控制移动、但是点击无效 3、睡眠唤醒后键盘无法使用，只能强制关机 以下是一些截图，还请帮忙分析一下是什么原因？ ![image](https://user-images.githubusercontent.com/117557199/200452296-4453dae7-6a1d-4ffa-aff3-358ba5374a0b.png) ![image](https://user-images.githubusercontent.com/117557199/200452376-53b5f999-8926-4842-8583-f0a66697c76a.png) ![image](https://user-images.githubusercontent.com/117557199/200452414-94678f5d-51ef-4105-933f-9241f8afb1e6.png) ![image](https://user-images.githubusercontent.com/117557199/200450440-9bdefe02-49fb-4ef2-8cfa-9d97876f0b25.png) ![image](https://user-images.githubusercontent.com/117557199/200451935-09cd048d-60ed-4230-86da-a26d339a2afa.png) [跑码.txt](https://github.com/mytianer/gs65-9sd-hackintosh/files/9956853/default.txt)

我的配置里蓝牙驱动没有打开，其它问题解决了吗。我升了vetura之后感觉问题挺多的，你的怎么样？

**Comment by mytianer** [comment]
我的配置里蓝牙驱动没有打开，其它问题解决了吗。我升了vetura之后感觉问题挺多的，你的怎么样？

**Comment by Orz-Orz-L** [comment]
目前功能都能用，但是有些不稳定，有时候开机wifi打不开，有时候蓝牙打不开，但是重启之后又都好了
